version: '3'

services:
  php:
    build:
      context: ./build/php-fpm
    ports:
      - "0.0.0.0:9009:9000"
    volumes:
      - .:/var/www/app

  nginx:
    build:
      context: ./build/nginx
    links:
      - php
    ports:
      - "8086:80"
    volumes:
      - .:/var/www/app
      - ./build/nginx/logs:/var/log/nginx/

  redis:
    image: redis:6-alpine
    command: --port 6379
    ports:
      - "6399:6379"
    volumes:
      - ./build/package/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    environment:
      - STORAGE_TYPE=persistent
    expose:
      - 6379

volumes:

  redis_data: